version: '3.8'
services:
  db:
    image: postgres:17
    container_name: hibernate-db
    restart: always
    environment:
      POSTGRES_USER: hibernate
      POSTGRES_PASSWORD: hibernate
      POSTGRES_DB: bookshelf
    ports:
      - "5432:5432"
